name: Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
    - name: Pront gretting
      run: echo "hellow world"
    -name: Print good bye
      run: echo "Done bye"
